services:
  backend:
    container_name: backend
    restart: always
    build: 
      context: ./backend
      dockerfile: docker_backend/DockerFile
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis                       # Ensure Redis starts before backend.
    volumes:
      - ./backend/:/usr/src/app/
      - ./shared:/shared
    environment:                    # Environment variables to configure Redis connection.
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_PASSWORD: dummy-pass
    networks:
      - app-network

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_DATABASE: vuedjango
      MARIADB_HOST: db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - 3308:3306
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - data-volume:/data
    networks:
      - app-network

  frontend:
    container_name: frontend
    restart: always
    build: 
      context: ./frontend
      dockerfile: docker_frontend/DockerFile
    ports:
      - 5173:5173
    volumes:
      - ./frontend/frontend:/usr/src/app
      - /usr/src/app/node_modules
    command: "npm run dev -- --host --port 5173"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:                         # Declare the Redis volume.
