services:
  backend:
    container_name: backend
    restart: always
<<<<<<< HEAD
    image: ${DOCKER_USERNAME}/${DOCKER_BACKEND_IMAGE}
=======
    build: 
      context: ./backend
      dockerfile: docker_backend/DockerFile
>>>>>>> 9136196204d339f7f76ab41d096b5c120d83e8a4
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - app-network

  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
<<<<<<< HEAD
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_HOST: ${MARIADB_HOST}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
=======
      MARIADB_DATABASE: vuedjango
      MARIADB_HOST: db
      MARIADB_ROOT_PASSWORD: root
      MARIADB_USER: root
      MARIADB_PASSWORD: root
>>>>>>> 9136196204d339f7f76ab41d096b5c120d83e8a4
    ports:
    - 3308:3306       # 3308 for local computer and 3306 for container
    networks:
      - app-network

  frontend:
    container_name: frontend
    restart: always
<<<<<<< HEAD
    image: ${DOCKER_USERNAME}/${DOCKER_FRONTEND_IMAGE}
=======
    build: 
      context: ./frontend
      dockerfile: docker_frontend/DockerFile
>>>>>>> 9136196204d339f7f76ab41d096b5c120d83e8a4
    ports:
      - 5173:80
    networks:
    - app-network

networks:
  app-network:
    driver: bridge