# Pull official base image
FROM python:3.12

# Set work directory
WORKDIR /usr/src/app

# Set environment variables
ENV TESSDATA_PREFIX=/usr/share/tesseract-ocr/5/tessdata/

# Install dependencies
RUN apt-get update && \
    apt-get install -y \
    tesseract-ocr \
    libtesseract-dev \
    gcc \
    python3-dev \
    libjpeg-dev \
    zlib1g-dev \
    && apt-get clean

RUN pip install --upgrade pip

# Copy requirements.txt and install Python dependencies
COPY requirements.txt ./
RUN pip install -v --no-cache-dir -r requirements.txt

# Copy project files
COPY . .

# Expose port for Django
EXPOSE 8000

# Start the Django server using Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]
