# pull official base image
FROM python:latest

#set work directory
WORKDIR /usr/src/app

# #set environment variables
# ENV PYTHONDONWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1

# install dependencies
RUN apt-get update && apt-get install -y default-mysql-client default-libmysqlclient-dev
RUN pip install --upgrade pip
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .
EXPOSE 8000

#CMD [ "python", "manage.py", "runserver", "0.0.0.0:8000" ]
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "backend.wsgi:application"]