# Build stage
FROM node:lts-alpine as build-stage
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from the correct path
COPY /frontend/package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application files
COPY ./frontend/ .

# Start the application in development mode
CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]

# Expose the port your Vue.js application runs on
EXPOSE 5173
