# Build stage
FROM node:lts-alpine as build-stage
WORKDIR /usr/src/app

# Copy package.json and package-lock.json from the correct path
COPY /frontend/package*.json ./

# Install dependencies
RUN npm update npm install

# Copy the rest of the application files
COPY ./frontend/ .

RUN npm run build-only
