# Workflow name
name: continuous integration

# Define when to trigger the Workflow
on:
  push:
    branches:
    - create-docker

#jobs to run
jobs:
  build:
    # Name of the job
    name: Build and Test
    # Platform to run the job on
    runs-on: ubuntu-latest
    # Define steps to execute
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v1
      
      - name: debug message
        run: echo "This is debugging message" 

      # Login to docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        
      # Build images and push docker images
      - name: Build and push Docker images
        uses: docker/build-push-action@v2
        with: 
          context: ./
          push: true
          dockerfile: ./Dockerfile
          tags: 10404/vuedango:latest
      
