# Workflow name
name: continuous integration

# Define when to trigger the Workflow
on:
  push:
    branches:
    - create-docker

#jobs to run
jobs:
  build:
    # Name of the job
    name: Build and Test
    # Platform to run the job on
    runs-on: ubuntu-latest
    # Define steps to execute
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v3
      
      # Install docker compose
      # - name: Install Docker Compose
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get install -y docker-compose

      - name: debug message
        run: echo "This is debugging message" 

      # Login to docker
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Debug: List frontend directory and paths
      - name: List project root
        run: ls -R ./

      # Debug: List frontend directory contents
      - name: List frontend directory contents
        run: ls -R ./frontend

      # Build and push frontend Docker image    
      - name: Build and push frontend Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./frontend 
          push: true
          file: docker_frontend/DockerFile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vue-django-frontend:latest
      # Build images and push docker images
      # - name: Build and push Docker images
      #  run: echo "Building and pushing images"

      # # Build frontend image
      # - name: Build frontend image
      #   run: |
      #     docker build -t vue-django-frontend ../frontend/docker_frontend/DockerFile

      # # Build backend image
      # - name: Build backend image
      #   run: |
      #     docker build -t vue-django-backend ../backend/docker_backend/DockerFile

      # # Push frontend Image
      # - name: Push frontend image
      #   run: |
      #     docker tag vue-django-frontend ${{ secrets.DOCKERHUB_USERNAME }}/vue-django-frontend:latest 
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/vue-django-frontend:latest

      # # Push backend image
      # - name: Push backend image
      #   run: | 
      #     docker tag vue-django-backend ${{ secrets.DOCKERHUB_USERNAME }}/vue-django-backend:latest 
      #     docker push ${{ secrets.DOCKERHUB_USERNAME }}/vue-django-backend:latest

